### ISSUE TITLE
PO compatibility issues

### ISSUE THREAD

**Issue by nfsmaniac** [An-dz/PurePO2JSON#1]
Hi,
according to
https://forum.vivaldi.net/topic/11926/general-discussion-english/61
I wanted to create some development/debugging version of PO, where fuzzy entries (marked for review in Weblate) will be unmarked as fuzzy and msgstr will have "(!)" before the string to have some UI feedback.

Unfortunately if I want to use your PurePO2JSON tool with the edited file, CPU has constant about 20% usage and nothing is converted even after longer time.
The original file is OK.

I am sending original and edited PO, there are some more differences (longer strings are less or more "multilined").
But I think it's gettext valid.

[po_files.zip](https://github.com/An-dz/PurePO2JSON/files/737706/po_files.zip)

**Comment by An-dz** [comment]
The problem is that your file has Windows line endings \r\n, I don't know why you generated it with CRLF but I'll fix it anyway. But it may take a while, it's a boring thing to fix.
